# Generated by Django 5.2 on 2025-06-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('release_year', models.IntegerField()),
                ('url', models.URLField()),
                ('poster', models.URLField(blank=True, null=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mood')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube', models.URLField()),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mood')),
            ],
        ),
    ]
